tasks:
  - name: SendInvitations
    description: Send party invitations to friends and ask for their availability (time, date, and place preferences).
    expected_output: A list of responses from invitees, including their availability details.
    agent: InvitationAgent
    inputs:
      - friends_list
      - invitation_template
    output_file: responses.json  # Stores collected responses for later use.

  - name: DetermineSchedule
    description: Analyze responses from invitees to determine the optimal time, date, and place for the party.
    expected_output: A proposed schedule with the best time, date, and place based on collective preferences.
    agent: SchedulerAgent
    inputs:
      - responses
    output_file: proposed_schedule.json  # Stores the proposed schedule.

  - name: SendConfirmations
    description: Share the proposed schedule with invitees and collect their confirmations.
    expected_output: A list of confirmations indicating whether invitees agree with the schedule.
    agent: ConfirmationAgent
    inputs:
      - friends_list
      - proposed_schedule
    output_file: confirmations.json  # Stores confirmations for review.

  - name: RenegotiateSchedule
    description: Resolve any disagreements regarding the proposed schedule by collecting updated preferences.
    expected_output: An updated schedule that works for all invitees.
    agent: NegotiationAgent
    inputs:
      - confirmations
      - proposed_schedule
    output_file: final_schedule.json  # Stores the final, agreed-upon schedule.
