create_invite_task:
  description: >
    Create text for email in which you invite a {guest_name} to drink a beer. 
    Ask invited guest about date, time and place in which he would like to meet.
    On top of text create title for email.
  expected_output: >
    Text with a content for email. On top, email title should be placed.
  agent: emails_creator
  output_file: invitation.txt

# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
